### ISSUE TITLE
Pretrained Models

### ISSUE THREAD

**Issue by Blinorot** [spkgyk/RTFS-Net#2]
Dear @spkgyk,

Thank you again for making the implementation public. Could you, please, also upload the checkpoints for RTFS-Net-12,16,20 (on LRS-2)? They would be great for comparison purposes.

Thank you in advance!

**Comment by spkgyk** [comment]
These larger models were trained on an external server we no longer have access to due to associated costs. The data and code have been made fully available, please let us know if you have any issues running the code.

**Comment by Blinorot** [comment]
Is there a chance that you have checkpoints for the smaller models (4-6) then?

The code is great, thank you! We just wanted to avoid spending compute time on reproducing checkpoints, if possible

**Comment by spkgyk** [comment]
I have the weights for RTFS-Net 4 and 12, but I have refactored the code in order to tidy things up and improve readability, meaning the weights are incompatible. If you want to spend the time to make them compatible, I have attached them, but I think it would probably be quicker to train yourself. 

[weights.zip](https://github.com/spkgyk/RTFS-Net/files/15024452/weights.zip)

Note that smaller batch sizes result in better performance.

**Comment by Blinorot** [comment]
Thank you very much!

> Note that smaller batch sizes result in better performance

You mean it is better to use less than 4(per GPU)x8(number of GPUs)=32 (taken from the paper) for the batch size?

**Comment by spkgyk** [comment]
Yes, I realized after the paper was published that using batch size 3 x 8 or 2 x 8 gives slightly increased performance.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by world2025** [comment]
@spkgyk 你好，可以提供一个推理脚本吗，谢谢

**Comment by world2025** [comment]
> I have the weights for RTFS-Net 4 and 12, but I have refactored the code in order to tidy things up and improve readability, meaning the weights are incompatible. If you want to spend the time to make them compatible, I have attached them, but I think it would probably be quicker to train yourself.
> 
> [weights.zip](https://github.com/spkgyk/RTFS-Net/files/15024452/weights.zip)
> 
> Note that smaller batch sizes result in better performance.

请问下需要改动很大吗
